DecoratingAndDIY = [
        
	"Decorating Offers",
	"New Decorating & DIY Range",
	"Wallpaper",
	"Shop by colour",
	"Shop by style",
	"Shop by room",
	"View All Categories ",
	"Paint & Woodcare",
	"Interior Paint & Woodcare",
	"Exterior Paint & Woodcare",
	"Primer & Undercoat",
	"Specialist Paint",
	"Metal Paint",
	"View All Categories ",
	"Decorating Tools & Supplies",
	"Paint Brushes & Rollers",
	"Wallpaper Preparation Tools",
	"Glues & Adhesives",
	"Scrapers, Trowels & Knives",
	"View All Categories ",
	"Hardware",
	"Doors & Furniture Hardware",
	"Screws",
	"Nails",
	"Nuts, Bolts & Washers",
	"Plugs & Fixings",
	"View All Categories",
	"Power Tools & Accessories",
	"Hand Tools",
	"Electrical",
	"Switches & Sockets",
	"Smart Home Technology",
	"Cable Reels & Extension Leads",
	"Door Bells, Alarms & Sensors",
	"Batteries & Chargers",
	"View All Categories",
	"Sticky Back Plastic",
	"Car Care",
	"Car Maintenance",
	"Car Cleaning",
	"Car Accessories",
	"View All Categories",
	"Home Security & Safety",
	"Door Locks & Latches",
	"Padlocks",
	"View All Categories",
	"Shelving, Hooks & Hanging",
	"Home Building & Maintenance",
	"Equipment & Safety Clothing",
	"Step Stools & Ladders",
	"Tool Boxes, Bags & Organisers",
	"View All Categories",

]

