GuardenOutdoorLving = [

	"Exterior Paint",
	"Garden Furniture Paint",
	"Shed & Fence Treatment",
	"Masonry Paint",
	"Exterior Wood Paint, Stain & Varnish",
	"View All Categories ",
	"Lawn & Plant Care",
	"Weed Killer & Weed Guards",
	"Plant Food & Fertilisers",
	"Lawn Seed & Fertilisers",
	"View All Categories ",
	"Planting & Growing",
	"Seeds & Bulbs",
	"Compost",
	"Plant Pots & Saucers",
	"Raised Beds",
	"View All Categories ",
	"Fence Panels & Posts",
	"Sheds & Shed Bases",
	"Watering & Hose Pipes",
	"Hose Pipes",
	"Watering Cans & Sprayers",
	"Watering Guns & Sprinklers",
	"Water Butts & Accessories",
	"View All Categories ",
	"Garden Tools",
	"Spades & Trowels",
	"Shears & Secateurs",
	"Rakes",
	"View All Categories ",
	"Outdoor Lighting",
	"Security Lighting",
	"Solar Lights",
	"Wall Lights",
	"View All Categories ",
	"Lawn Mowers",
	"Outdoor Living",
	"Garden Furniture Covers",
	"BBQs & Accessories",
	"Picnicware",
	"View All Categories ",
	"Wildlife",
	"Wild Birds",
	"Pond Fish Food & Supplies",
	"Chicken Food & Supplies",
	"View All Categories",

]
