HealthandBeauty = [

	"Christmas Gifts",
	"Toiletries",
	"Deodorants & Antiperspirants",
	"Shower Gel & Body Wash",
	"Shampoo & conditioner",
	"Sanitary & Bladder Control",
	"Razors & Hair Removal",
	"Hand Wash & Soap",
	"View All Categories ",
	"Dental Care",
	"Toothpaste",
	"Toothbrushes",
	"Mouthwash",
	"View All Categories ",
	"Hair Care & Styling",
	"Hair Spray, Gel & Mousse",
	"Hair Serum & Treatments",
	"Hair Accessories",
	"View All Categories ",
	"Skin Care",
	"Body Moisturisers",
	"Self Tanning",
	"Face Care",
	"Hand Cream",
	"Sun Cream & After Sun",
	"View All Categories ",
	"Make Up",
	"Lips",
	"Face",
	"Eyes",
	"Nails",
	"View All Categories ",
	"Eye Care",
	"Eye Drops & Sprays",
	"Reading Glasses",
	"Lens Cleaning",
	"View All Categories ",
	"Foot Care",
	"Insoles & Cushions",
	"Creams & Sprays",
	"View All Categories ",
	"Perfume & Aftershave",
	"Perfume",
	"Aftershave",
	"View All Categories ",
	"Health & Wellbeing",
	"Coughs, Cold & Flu",
	"Pain Relief",
	"First Aid",
	"Allergies & Hayfever",
	"View All Categories ",
	"Baby & Pregnancy",
	"Holiday Shop",
	"Health & Beauty Offers	",

]
