HouseholdCleaning = [

	"Laundry & Ironing",
	"Detergents",
	"Fabric Conditioners",
	"Scent Boosters & Fresheners",
	"Irons",
	"Ironing Boards & Covers",
	"Clothes Airers & Dryers",
	"Washing Lines",
	"Hangers",
	"View All Categories ",
	"Floorcare",
	"Vacuum Cleaners & Bags",
	"Carpet Cleaners & Fresheners",
	"Brushes & Brooms",
	"Mops, Heads & Refills",
	"View All Categories ",
	"Cleaning Products",
	"Multi purpose Cleaners",
	"Kitchen & Oven Cleaners",
	"Drain Cleaners & Unblockers",
	"Furniture Polish & Cleaners",
	"Glass Cleaners",
	"Bleach",
	"Floor Cleaners",
	"View All Categories ",
	"Cleaning Supplies",
	"Cloths",
	"Dusters",
	"Sponges & Scourers",
	"Brushes & Brooms",
	"Mops, Mop Heads & Refills",
	"Washing Up Liquid",
	"Dishwasher Tablets & Rinse Aids",
	"View All Categories ",
	"Kitchen Rolls, Toilet Rolls & Tissues",
	"Kitchen Rolls",
	"Toilet Rolls & Wipes",
	"Tissues",
	"View All Categories ",
	"Air Fresheners",
	"Scented Candles",
	"Wax Melts",
	"Room Sprays",
	"Air Freshener Refills",
	"View All Categories ",
	"Insect & Pest Control",
	"Clothes Dyes",
	"Cleaning & Household Offers",

]
