KitchenDining = [

	"Kitchen Appliances",
	"Microwaves",
	"Kettles",
	"Toasters",
	"Cookers & Fryers",
	"View All Categories ",
	"Cookware",
	"Pots & Pans",
	"Cooking Utensils",
	"Oven & Roasting",
	"Casserole Pans & Stock Pots",
	"Tableware",
	"Dinner Sets",
	"Cutlery",
	"Glasses",
	"Mugs & Cups",
	"Table Cloths & Mats",
	"View All Categories ",
	"Food Storage",
	"Storage Jars",
	"Food Boxes",
	"Flasks & Travel Mugs",
	"View All Categories",
	"Kitchen Organisers",
	"Serveware",
	"Teapots & Coffee Pots",
	"Serving Bowls & Dishes",
	"View All Categories",
	"Water Jugs & Filters",
	"Home Brewing",
	"Food Preparation",
	"Kitchen Utensils",
	"Chopping Boards",
	"Scales & Measuring",
	"View All Categories",
	"Baking & Decorating",
	"Baking Trays, Tins & Cases",
	"Cake Stands & Trays",
	"View All Categories",
	"Kitchen Accessories & Linen",
	"Oven Gloves & Aprons",
	"Tea Towels",
	"Kitchen Accessories",
	"Kitchen Bins",
	"View All Categories",
	"Kitchen Collections",
	"Copper Kitchen",
	"Grey Kitchen",
	"Black Matt Kitchen",
	"Sticky Back Plastic",
	"Dining Sets & Chairs",
	"Kitchen Offers",

]

