offers = [ 

	"Toys Offers",
	"Toys - 2 For £15",
	"View All Categories ",
	"Home & Kitchen Offers",
	"Storage - Up to 30% off",
	"Throws - Up to 30% Off",
	"View All Categories ",
	"Stationery & Craft Offers",
	"Bic pens - Save up to 50%",
	"Ink Cartridges - Save 25%",
	"View All Categories ",
	"Pets Offers",
	"Cat Food - Up to 30% off",
	"Dog Food - Up to 25% off",
	"Dog Treats - Up to 40% off",
	"View All Categories ",
	"Cleaning & Household Offers",
	"Glade - Up to half price",
	"Laundry Care - Up to half price",
	"Cleaning Products - 2 For £1.80",
	"View All Categories ",
	"Health & Beauty Offers",
	"Dental Care - Up to half price",
	"Bath & Shower - Up to half price",
	"Save on baby toiletries",
	"Decorating & DIY Offers",
	"Wallpaper -Save 20%",
	"Dulux Paint - 2 For £24",
	"Wilko Durable- Was £15 Now £9",
	"View All Categories",

]
