pets = [

	"Dogs & Puppies",
	"Dog Food",
	"Dog Treats",
	"Dog Bowls & Storage",
	"Dog Collars & Leads",
	"Dog Beds & Crates",
	"Dog Toys",
	"Dog Training & Waste Bags",
	"Dog Healthcare",
	"Dog Shampoo & Grooming",
	"View All Categories ",
	"Cats & Kittens",
	"Cat Food",
	"Cat Treats",
	"Cat Beds & Carriers",
	"Cat Litter, Trays & Disposal",
	"Cat Healthcare",
	"Cat Toys & Scratching Posts",
	"Cat Grooming & Collars",
	"View All Categories ",
	"Small Pets",
	"Small Pet Food",
	"Small Pet Treats",
	"Bowls & Bottles",
	"Housing, Bedding & Carriers",
	"Small Pets Toys",
	"Small Pets Healthcare",
	"Pet Cleaning Supplies",
	"Wildlife",
	"Wild Bird Food",
	"Wild Bird Feeders",
	"Bird Houses & Tables",
	"Chicken Food & Supplies",
	"Pond Fish Food & Supplies",
	"View All Categories",

]

