StationaryCraft = [

	"Pens & Pencils",
	"Pens",
	"Pencils",
	"Colouring Pens",
	"Pencil Cases",
	"View All Categories",
	"Notebooks, Pads & Organisers",
	"Notebooks & Pads",
	"Diaries, Planners & Organisers",
	"Post It Notes & Memo Pads",
	"View All Categories",
	"Desk Supplies",
	"Paper Clips & Rubber Bands",
	"Adhesive Tape",
	"Erasers",
	"View All Categories",
	"Desk Storage & Filing",
	"Computer Accessories",
	"Memory Cards",
	"Mobile & Tablet Accessories",
	"Laptop Bags & Mobile Cases",
	"Speakers & Headphones",
	"Charging Cables & Adapters",
	"View All Categories ",
	"Printers, Ink & Paper",
	"Printers & Ink Cartridges",
	"Photocopy & Printing Paper",
	"Paper Shredding & Laminating",
	"View All Categories ",
	"Packaging & Mailing",
	"Envelopes & Mailing Bags",
	"Packaging Tape & Bubble Wrap",
	"Cardboard Boxes",
	"View All Categories ",
	"Calculators",
	"Stationery Collections",
	"Discovery Collection",
	"Stay Magic Collection",
	"Sentiments Collection",
	"Treasured Collection",
	"Hypernatural Collection",
	"View All Categories ",
	"Arts & Crafts",
	"Party & Gift Wrap",
	"Party Tableware & Serving",
	"Party Decorations",
	"Invitations, Gift wrap & Bags",
	"View All Categories ",
	"Rulers & Geometry Sets",
	"Stationery & Craft Offers",

]
