output = [
	"Title: Gift Sets | Products: 93",
	"Title: Chocolate & Sweets | Products: 176",
	"Title: Christmas Pet Gifts | Products: 35",
	"Title: Gifts For Him | Products: 74",
	"Title: Gifts For Her | Products: 118",
	"Title: Gifts for Kids | Products: 60",
	"Title: Christmas Gift Wrap & Bags | Products: 92",
	"Title: Gift Wrap & Tags | Products: 58",
	"Title: Christmas Gift Bags | Products: 34",
	"Title: Christmas Trees | Products: 15",
	"Title: 5ft Christmas Trees | Products: 1",
	"Title: 6ft Christmas Trees | Products: 7",
	"Title: 7ft Christmas Trees | Products: 2",
	"Title: Christmas Lights | Products: 27",
	"Title: Christmas Home Decor | Products: 48",
	"Title: Christmas Bedding | Products: 8",
	"Title: Christmas Decorations | Products: 155",
	"Title: Christmas Dining | Products: 35",
	"Title: Calendars & Diaries | Products: 40",
	"Title: Christmas Crafts | Products: 32",
	"Title: Christmas Offers | Products: 228",
	"Title: 3 for 2 Christmas Decorations | Products: 141",
	"Title: 3 for 2 Christmas Gift Wrap | Products: 87",
	"D'oh",
	"Title: Table Lamps | Products: 56",
	"D'oh",
	"Title: Light Bulbs | Products: 146",
	"Title: Outdoor Lighting | Products: 14",
	"D'oh",
	"Title: Mirrors | Products: 77",
	"Title: Clocks | Products: 31",
	"Title: Vases & Ornaments | Products: 106",
	"Title: Candles, Diffusers & Potpourri | Products: 122",
	"Title: Heating & Cooling | Products: 56",
	"Title: Fans | Products: 5",
	"Title: Moisture Absorbers | Products: 14",
	"D'oh",
	"D'oh",
	"Title: Duvets | Products: 35",
	"Title: Pillows | Products: 17",
	"Title: Pillow Cases | Products: 29",
	"Title: Cushions & Throws | Products: 147",
	"Title: Rugs & Doormats | Products: 46",
	"Title: Curtains | Products: 126",
	"Title: Blinds | Products: 80",
	"Title: Home Security & Safety | Products: 120",
	"Title: Door Bells | Products: 13",
	"Title: Door Locks & Latches | Products: 23",
	"Title: Padlocks | Products: 33",
	"Title: Smoke & House Alarms | Products: 6",
	"Title: Beds & Mattresses | Products: 184",
	"D'oh",
	"D'oh",
	"D'oh",
	"D'oh",
	"D'oh",
	"Title: Ottomans & Storage Cubes | Products: 26",
	"Title: Towels & Bathmats | Products: 128",
	"Title: Toilet Seats | Products: 14",
	"Title: Bathroom accessories | Products: 41",
	"D'oh",
	"Title: Bathroom Bins | Products: 14",
	"Title: Bathroom Storage | Products: 24",
	"Title: Home Living Offers | Products: 90",
	"Title: Duvet covers | Products: 179",
	"Title: Kitchen Appliances | Products: 63",
	"Title: Microwaves | Products: 5",
	"Title: Kettles | Products: 19",
	"Title: Toasters | Products: 18",
	"Title: Cookers & Fryers | Products: 6",
	"Title: Cookware | Products: 143",
	"Title: Pots & Pans | Products: 71",
	"Title: Cooking Utensils | Products: 34",
	"Title: Oven & Roasting | Products: 36",
	"Title: Casserole Pans & Stock Pots | Products: 11",
	"D'oh",
	"D'oh",
	"D'oh",
	"D'oh",
	"Title: Mugs & Cups | Products: 52",
	"Title: Table Cloths & Mats | Products: 25",
	"Title: Food Storage | Products: 140",
	"Title: Storage Jars | Products: 42",
	"Title: Food Boxes | Products: 25",
	"Title: Flasks & Travel Mugs | Products: 21",
	"Title: Kitchen Organisers | Products: 37",
	"D'oh",
	"Title: Teapots & Coffee Pots | Products: 9",
	"Title: Serving Bowls & Dishes | Products: 21",
	"Title: Water Jugs & Filters | Products: 18",
	"Title: Home Brewing | Products: 74",
	"D'oh",
	"Title: Kitchen Utensils | Products: 37",
	"Title: Chopping Boards | Products: 11",
	"Title: Scales & Measuring | Products: 14",
	"Title: Baking Trays, Tins & Cases | Products: 43",
	"Title: Cake Stands & Trays | Products: 8",
	"D'oh",
	"Title: Oven Gloves & Aprons | Products: 7",
	"D'oh",
	"D'oh",
	"Title: Kitchen Bins | Products: 10",
	"Title: Kitchen Collections | Products: 78",
	"Title: Copper Kitchen | Products: 40",
	"Title: Grey Kitchen | Products: 25",
	"Title: Black Matt Kitchen | Products: 14",
	"Title: Sticky Back Plastic | Products: 85",
	"Title: Dining Sets & Chairs | Products: 38",
	"Title: Kitchen Offers | Products: 19",
	"Title: New Kitchen | Products: 185",
	"Title: Christmas Gifts | Products: 93",
	"Title: Deodorants & Antiperspirants | Products: 162",
	"Title: Shower Gel & Body Wash | Products: 95",
	"Title: Shampoo & conditioner | Products: 200",
	"Title: Sanitary & Bladder Control | Products: 92",
	"Title: Razors & Hair Removal | Products: 132",
	"Title: Hand Wash & Soap | Products: 48",
	"Title: Dental Care | Products: 202",
	"Title: Toothpaste | Products: 78",
	"Title: Toothbrushes | Products: 61",
	"Title: Mouthwash | Products: 33",
	"Title: Hair Care & Styling | Products: 549",
	"Title: Hair Spray, Gel & Mousse | Products: 77",
	"Title: Hair Serum & Treatments | Products: 9",
	"Title: Hair Accessories | Products: 49",
	"Title: Skin Care | Products: 350",
	"D'oh",
	"Title: Self Tanning | Products: 16",
	"Title: Face Care | Products: 196",
	"Title: Hand Cream | Products: 24",
	"Title: Sun Cream & After Sun | Products: 80",
	"Title: Lips | Products: 303",
	"Title: Face | Products: 390",
	"Title: Eyes | Products: 300",
	"Title: Nails | Products: 27",
	"Title: Eye Care | Products: 34",
	"Title: Eye Drops & Sprays | Products: 8",
	"Title: Reading Glasses | Products: 24",
	"Title: Lens Cleaning | Products: 2",
	"Title: Foot Care | Products: 42",
	"Title: Insoles & Cushions | Products: 17",
	"Title: Creams & Sprays | Products: 16",
	"Title: Perfume & Aftershave | Products: 25",
	"Title: Perfume | Products: 9",
	"Title: Aftershave | Products: 15",
	"Title: Coughs, Cold & Flu | Products: 73",
	"Title: Pain Relief | Products: 66",
	"Title: First Aid | Products: 52",
	"Title: Allergies & Hayfever | Products: 10",
	"Title: Holiday Shop | Products: 189",
	"Title: Health & Beauty Offers | Products: 707",
	"Title: Christmas Gifts | Products: 93",
	"Title: Pre-School & Learning | Products: 70",
	"Title: Wooden Toys | Products: 11",
	"Title: Let's Pretend | Products: 21",
	"Title: Little Steps | Products: 13",
	"Title: Bikes & Accessories | Products: 147",
	"Title: Kids Bikes | Products: 16",
	"Title: Mountain Bikes | Products: 10",
	"Title: Folding & Road Bikes | Products: 7",
	"Title: Balance Bikes | Products: 2",
	"D'oh",
	"Title: Wilko Blox Construction | Products: 6",
	"Title: Wilko Blox Police, Fire & Rescue | Products: 16",
	"Title: Wilko City Life & Vehicles | Products: 22",
	"Title: Wilko Blox Accessories | Products: 9",
	"Title: Fancy Dress & Role Play | Products: 31",
	"Title: Play Shop | Products: 3",
	"Title: Dress Up | Products: 5",
	"Title: Role Play | Products: 25",
	"Title: Dough & Modelling | Products: 10",
	"Title: Board Games & Jigsaws | Products: 21",
	"Title: Dolls & Accessories | Products: 28",
	"Title: Soft Toys | Products: 26",
	"Title: Vehicles & Play Sets | Products: 21",
	"Title: Action Toys, Animals & Play Sets | Products: 32",
	"Title: Pocket Money Toys | Products: 19",
	"Title: Batteries | Products: 66",
	"Title: Toys Offers | Products: 25",
	"Title: Toys & Games - 2 for £15 | Products: 17",
	"Title: New Toy Ranges | Products: 111",
	"Title: Decorating Offers | Products: 613",
	"Title: New Decorating & DIY Range | Products: 156",
	"Title: Exterior Paint & Woodcare | Products: 118",
	"Title: Primer & Undercoat | Products: 30",
	"Title: Specialist Paint | Products: 32",
	"Title: Metal Paint | Products: 98",
	"Title: Paint Brushes & Rollers | Products: 70",
	"Title: Wallpaper Preparation Tools | Products: 19",
	"Title: Glues & Adhesives | Products: 69",
	"Title: Scrapers, Trowels & Knives | Products: 25",
	"Title: Hardware | Products: 401",
	"Title: Doors & Furniture Hardware | Products: 198",
	"Title: Screws | Products: 35",
	"Title: Nails | Products: 27",
	"Title: Nuts, Bolts & Washers | Products: 10",
	"Title: Plugs & Fixings | Products: 93",
	"Title: Power Tools & Accessories | Products: 104",
	"Title: Hand Tools | Products: 147",
	"Title: Electrical | Products: 346",
	"Title: Switches & Sockets | Products: 60",
	"Title: Smart Home Technology | Products: 14",
	"Title: Cable Reels & Extension Leads | Products: 24",
	"Title: Door Bells, Alarms & Sensors | Products: 23",
	"Title: Batteries & Chargers | Products: 66",
	"Title: Sticky Back Plastic | Products: 85",
	"Title: Car Care | Products: 238",
	"D'oh",
	"Title: Car Cleaning | Products: 62",
	"Title: Car Accessories | Products: 51",
	"Title: Home Security & Safety | Products: 120",
	"Title: Door Locks & Latches | Products: 23",
	"Title: Padlocks | Products: 33",
	"Title: Shelving, Hooks & Hanging | Products: 124",
	"Title: Home Building & Maintenance | Products: 75",
	"Title: Equipment & Safety Clothing | Products: 31",
	"Title: Step Stools & Ladders | Products: 5",
	"Title: Tool Boxes, Bags & Organisers | Products: 17",
	"Title: Wallpaper Offers | Products: 390",
	"D'oh",
	"D'oh",
	"Title: Storage Drawers | Products: 28",
	"Title: Storage Boxes | Products: 57",
	"Title: Storage Baskets & Hampers | Products: 39",
	"Title: Kitchen Trolleys | Products: 6",
	"Title: Kitchen Organisers | Products: 37",
	"Title: Food Storage | Products: 140",
	"Title: Office Storage | Products: 29",
	"D'oh",
	"Title: Bathroom Storage | Products: 24",
	"Title: Storage Bags | Products: 10",
	"Title: Clothing Storage | Products: 9",
	"Title: Cardboard Boxes | Products: 11",
	"Title: Tool Bags & Organisers | Products: 17",
	"D'oh",
	"D'oh",
	"Title: Shed & Fence Treatment | Products: 17",
	"Title: Masonry Paint | Products: 28",
	"Title: Exterior Wood Paint, Stain & Varnish | Products: 73",
	"Title: Lawn & Plant Care | Products: 56",
	"Title: Weed Killer & Weed Guards | Products: 22",
	"Title: Plant Food & Fertilisers | Products: 19",
	"Title: Lawn Seed & Fertilisers | Products: 12",
	"Title: Planting & Growing | Products: 140",
	"Title: Seeds & Bulbs | Products: 94",
	"Title: Compost | Products: 7",
	"Title: Plant Pots & Saucers | Products: 16",
	"Title: Raised Beds | Products: 12",
	"Title: Fence Panels & Posts | Products: 16",
	"Title: Sheds & Shed Bases | Products: 31",
	"Title: Watering & Hose Pipes | Products: 17",
	"Title: Hose Pipes | Products: 2",
	"Title: Watering Cans & Sprayers | Products: 6",
	"Title: Garden Tools | Products: 27",
	"Title: Spades & Trowels | Products: 3",
	"Title: Shears & Secateurs | Products: 6",
	"Title: Rakes | Products: 2",
	"Title: Outdoor Lighting | Products: 14",
	"Title: Security Lighting | Products: 5",
	"Title: Solar Lights | Products: 5",
	"Title: Wall Lights | Products: 4",
	"Title: Lawn Mowers | Products: 12",
	"Title: Outdoor Living | Products: 68",
	"Title: Garden Furniture Covers | Products: 2",
	"Title: BBQs & Accessories | Products: 5",
	"Title: Picnicware | Products: 9",
	"Title: Wild Birds | Products: 102",
	"Title: Pond Fish Food & Supplies | Products: 7",
	"Title: Chicken Food & Supplies | Products: 8",
	"Title: Detergents | Products: 111",
	"Title: Fabric Conditioners | Products: 47",
	"Title: Scent Boosters & Fresheners | Products: 24",
	"Title: Irons | Products: 11",
	"Title: Ironing Boards & Covers | Products: 14",
	"Title: Clothes Airers & Dryers | Products: 16",
	"Title: Washing Lines | Products: 5",
	"Title: Hangers | Products: 15",
	"Title: Floorcare | Products: 140",
	"Title: Vacuum Cleaners & Bags | Products: 18",
	"Title: Carpet Cleaners & Fresheners | Products: 21",
	"Title: Brushes & Brooms | Products: 26",
	"Title: Mops, Heads & Refills | Products: 54",
	"Title: Cleaning Products | Products: 242",
	"Title: Multi purpose Cleaners | Products: 55",
	"Title: Kitchen & Oven Cleaners | Products: 29",
	"Title: Drain Cleaners & Unblockers | Products: 6",
	"Title: Furniture Polish & Cleaners | Products: 14",
	"Title: Glass Cleaners | Products: 6",
	"Title: Bleach | Products: 11",
	"Title: Floor Cleaners | Products: 13",
	"Title: Cleaning Supplies | Products: 174",
	"Title: Cloths | Products: 20",
	"Title: Dusters | Products: 8",
	"Title: Sponges & Scourers | Products: 30",
	"Title: Brushes & Brooms | Products: 26",
	"Title: Mops, Mop Heads & Refills | Products: 54",
	"Title: Washing Up Liquid | Products: 19",
	"Title: Dishwasher Tablets & Rinse Aids | Products: 27",
	"Title: Kitchen Rolls, Toilet Rolls & Tissues | Products: 65",
	"Title: Kitchen Rolls | Products: 20",
	"Title: Toilet Rolls & Wipes | Products: 27",
	"Title: Tissues | Products: 18",
	"Title: Air Fresheners | Products: 253",
	"Title: Scented Candles | Products: 40",
	"Title: Wax Melts | Products: 7",
	"Title: Room Sprays | Products: 92",
	"Title: Air Freshener Refills | Products: 88",
	"Title: Insect & Pest Control | Products: 41",
	"Title: Clothes Dyes | Products: 5",
	"Title: Cleaning & Household Offers | Products: 174",
	"Title: Shop new Glade air care | Products: 39",
	"Title: Dog Food | Products: 167",
	"Title: Dog Treats | Products: 167",
	"Title: Dog Bowls & Storage | Products: 16",
	"Title: Dog Collars & Leads | Products: 32",
	"Title: Dog Beds & Crates | Products: 36",
	"Title: Dog Toys | Products: 77",
	"Title: Dog Training & Waste Bags | Products: 20",
	"Title: Dog Healthcare | Products: 29",
	"Title: Dog Shampoo & Grooming | Products: 18",
	"Title: Cat Food | Products: 167",
	"Title: Cat Treats | Products: 57",
	"Title: Cat Beds & Carriers | Products: 11",
	"Title: Cat Litter, Trays & Disposal | Products: 13",
	"Title: Cat Healthcare | Products: 20",
	"Title: Cat Toys & Scratching Posts | Products: 32",
	"Title: Cat Grooming & Collars | Products: 14",
	"Title: Small Pets | Products: 101",
	"Title: Small Pet Food | Products: 35",
	"Title: Small Pet Treats | Products: 33",
	"Title: Bowls & Bottles | Products: 4",
	"Title: Housing, Bedding & Carriers | Products: 16",
	"Title: Small Pets Toys | Products: 7",
	"Title: Small Pets Healthcare | Products: 7",
	"Title: Pet Cleaning Supplies | Products: 30",
	"Title: Wild Bird Food | Products: 70",
	"Title: Wild Bird Feeders | Products: 29",
	"Title: Bird Houses & Tables | Products: 3",
	"Title: Chicken Food & Supplies | Products: 8",
	"Title: Pond Fish Food & Supplies | Products: 7",
	"Title: Domestic Bird Food & Supplies | Products: 17",
	"Title: Fish | Products: 67",
	"Title: Fish Food | Products: 15",
	"Title: Fish Tanks & Supplies | Products: 52",
	"D'oh",
	"Title: Filters & Pumps | Products: 14",
	"Title: Heaters & Thermometers | Products: 4",
	"Title: Reptiles Food & Supplies | Products: 23",
	"Title: Christmas Pet Gifts | Products: 35",
	"Title: Pets Offers | Products: 144",
	"Title: Pens & Pencils | Products: 180",
	"Title: Pens | Products: 80",
	"Title: Pencils | Products: 19",
	"D'oh",
	"Title: Pencil Cases | Products: 21",
	"Title: Notebooks, Pads & Organisers | Products: 169",
	"Title: Notebooks & Pads | Products: 88",
	"Title: Diaries, Planners & Organisers | Products: 46",
	"Title: Post It Notes & Memo Pads | Products: 13",
	"Title: Desk Supplies | Products: 88",
	"Title: Paper Clips & Rubber Bands | Products: 6",
	"Title: Adhesive Tape | Products: 9",
	"Title: Erasers | Products: 9",
	"Title: Desk Storage & Filing | Products: 73",
	"Title: Computer Accessories | Products: 189",
	"Title: Memory Cards | Products: 6",
	"Title: Mobile & Tablet Accessories | Products: 38",
	"Title: Laptop Bags & Mobile Cases | Products: 35",
	"Title: Speakers & Headphones | Products: 55",
	"Title: Charging Cables & Adapters | Products: 38",
	"Title: Printers, Ink & Paper | Products: 99",
	"Title: Printers & Ink Cartridges | Products: 83",
	"Title: Photocopy & Printing Paper | Products: 9",
	"Title: Paper Shredding & Laminating | Products: 7",
	"Title: Packaging & Mailing | Products: 36",
	"Title: Envelopes & Mailing Bags | Products: 15",
	"Title: Packaging Tape & Bubble Wrap | Products: 7",
	"Title: Cardboard Boxes | Products: 11",
	"Title: Calculators | Products: 5",
	"Title: Discovery Collection | Products: 25",
	"Title: Stay Magic Collection | Products: 24",
	"Title: Sentiments Collection | Products: 25",
	"Title: Treasured Collection | Products: 8",
	"Title: Hypernatural Collection | Products: 10",
	"Title: Party Tableware & Serving | Products: 78",
	"Title: Party Decorations | Products: 21",
	"Title: Invitations, Gift wrap & Bags | Products: 137",
	"Title: Rulers & Geometry Sets | Products: 9",
	"Title: Stationery & Craft Offers | Products: 108",
	"Title: Printer Ink Offers | Products: 29",
	"Title: Student Home Living | Products: 269",
	"Title: Bedroom Ideas | Products: 110",
	"Title: Kitchen Essentials | Products: 85",
	"Title: Storage Solutions | Products: 76",
	"Title: Bathroom Essentials | Products: 25",
	"Title: Stationery & Tech | Products: 451",
	"Title: Uni Stationery | Products: 258",
	"Title: Tech Essentials | Products: 193",
	"Title: Beds & Mattresses | Products: 184",
	"D'oh",
	"Title: Bookcases & Display Units | Products: 26",
	"Title: Computer Desks | Products: 7",
	"Title: Student Essentials | Products: 115",
	"Title: Cleaning & Tidying | Products: 47",
	"Title: DIY Essentials | Products: 21",
	"Title: Health & Beauty Essentials | Products: 47",
	"Title: Student Living Bundles | Products: 15",
	"Title: Student Living Offers | Products: 70",
	"Title: Halloween Decorations | Products: 51",
	"Title: Animated Decorations | Products: 2",
	"Title: Party Decorations | Products: 21",
	"Title: Animal Props | Products: 10",
	"Title: Pumpkins | Products: 7",
	"Title: Halloween Lighting | Products: 8",
	"Title: Halloween Partyware | Products: 10",
	"Title: Halloween Costumes | Products: 93",
	"Title: Vampire Costumes | Products: 9",
	"D'oh",
	"Title: Cheerleader Costumes | Products: 8",
	"Title: Surgeon Costumes | Products: 5",
	"Title: Monster Costumes | Products: 4",
	"Title: Cat Costumes | Products: 5",
	"Title: Nurse Costumes | Products: 4",
	"Title: Halloween Costume Accessories | Products: 38",
	"Title: Face Paint & Make Up | Products: 25",
	"Title: Loot Bags & Bowls | Products: 3",
	"Title: Toys Offers | Products: 25",
	"Title: Toys - 2 For £15 | Products: 17",
	"Title: Home & Kitchen Offers | Products: 70",
	"Title: Storage - Up to 30% off | Products: 14",
	"Title: Throws - Up to 30% Off | Products: 8",
	"Title: Stationery & Craft Offers | Products: 108",
	"Title: Bic pens - Save up to 50% | Products: 17",
	"Title: Ink Cartridges - Save 25% | Products: 29",
	"Title: Pets Offers | Products: 144",
	"Title: Cat Food - Up to 30% off | Products: 63",
	"Title: Dog Food - Up to 25% off | Products: 75",
]
